#+TITLE: aozora-proc.el ... 青空文庫プロセッサ
#+STARTUP: showall
#+AUTHOR: Taichi Kawabata <kawabata.taichi@gmail.com>

* aozora-proc.el について

  青空文庫の文法チェッカ・HTML5・LaTeXへの出力を行うツールです。

  本プログラムは、以下を目標として開発しています。

  - 解析表現文法の活用 :: 青空文庫注記を解析表現文法で文法チェック・解
                          析し、それに基づいてデータ化する。
  - モジュール化 :: 注記のパーザ・データ化部分・外部出力部分を分離し、
                    文法チェック・HTML5・HTML5縦書き・TeX・TeX縦書き・
                    Adobe InDesign (IDML) への出力に対応（予定）。
  - 小型化 :: ソースコード全体のサイズを小さくする。特にパーザは解析表
              現文法で表記することで、プログラムを簡素化する。移植性を
              重視し、処理速度は気にしない。
  - UCS対応 :: 非JIS漢字やアクセント付き欧文のUCS完全対応。（現状では青
               空文庫での利用が確認されている非JIS X 0208漢字8,000字程
               度に対応）
  - Emacs Lisp :: テキスト編集中に文法チェックを行えるようにする。
  - org-mode対応 :: org-mode 等の既存のアウトラインプロセッサの中で青空
                    文庫の注記を利用可能にする。
  - バッチ処理対応 :: シェルスクリプトからのバッチ処理が可能。

  本プログラムはまだ青空文庫の注記の一部しか対応していませんが、プログ
  ラム末尾のデータ出力設定部分を適当に拡張・変更することで、自由に拡張・
  カスタマイズ可能です。

* 使い方：

** 前準備

  1. Emacs 23.2 以降 (ucs-normalize.el が必要なため) と、peg.el
     (http://emacswiki.org) を用意し、load-pathに含まれるディレクトリ
     (/usr/local/share/emacs/site-lispなど）にインストールします。

  2. 《オプショナル》 漢字データベースのサイトから、外字データファイル
     aozora_gaiji_chuki.txt
     (http://kanji-database.sourceforge.net/aozora/gaiji.html) をダウン
     ロードし、適当な場所に入れます。

** コマンドラインでの使い方

   1. コマンドラインから、 --script オプションを使って起動します。
      以下は、複数のファイルを変換する例です。
 
      : % emacs --script aozora-proc.el -f <format> file1.txt file2.txt ...
 
      ここで、フォーマットは : `html-h', `tex-h' (横書き), `html-v',
      `tex-v' (縦書き) が選択できます。
 
      縦書きHTMLは、WebKit Nightly Builds 等のブラウザで確認できます。
 
      処理途中で文法エラーが見付かった場合は、エラー表示をした後、そこま
      での変換処理をてファイルに保存します。

      TeX版はまだ開発途上です。またマクロの衝突の問題により、いくつかの
      修飾が重なった場合は手で修正しなければならない場合があります。
 
   2. 単に注記の検証をしたい場合は、
 
      : % emacs --script aozora-proc.el file.txt
 
      としてください。注記に間違いがある場合はその行を表示します。（実際
      にはその前後の行で間違っている場合もあります。）
 
   3. 他の詳細なオプションについては、
 
      : % emacs --script aozora-proc.el -h
 
      で確認してください。

** Emacs での使い方

   1. M-x load-library aozora-proc 等で本ライブラリを読み込みます。
 
   2. 変換したいファイル（例：sample.txt）を開きます。
 
   3. 変換したいフォーマットに aozora-proc-method を設定します。
      例： (setq aozora-proc-method 'html-v)
 
   4. ファイルを検証したい場合は、M-x aozora-proc-parse とします。文法エ
      ラーがある場合はその箇所で停止します。
 
   5. HTML/TeX に変換する場合は、 M-x aozora-proc-markup とします。
 
   6. バッファ全体に対して変換する場合は、M-x aozora-proc-buffer を、ファ
      イルに対して処理をしたい場合は、M-x aozora-proc-file を実行します。

* 注意

  本プログラムを使うことによって生じるいかなる損失・損害についても作者
  は責任を負いません。

  本プログラムはまだコンセプトベースのα版です。要望があれば徐々に改良
  していきます。特に、TeXはルビやセクション、その他の修飾が重複するとほ
  とんどうまく動作しません。TeXは、eup-TeX＋金水マクロ等が必要で、また
  往々にして修正作業をしないとコンパイルできません。

* ライセンス

  - aozora-proc.el … GPL (文法部分はのぞく)
  - grammar.txt … BSD
